const CONSTANTS = {
  KAFKA_TOPIC: 'hotel-price-updates',
  AGENT_CONFIDENCE_THRESHOLD: 0.6,
  SLOW_RESPONSE_THRESHOLD_MS: 10000,
  FEEDBACK_LOOP_INTERVAL: '*/30 * * * *',
  PRICE_DROP_THRESHOLD_PCT: 0.20,
  MAX_CAMPAIGN_AGE_HOURS: 1,
  MOCK_METRICS: {
    SENT_MIN: 1000,
    SENT_MAX: 5000,
    OPEN_RATE_MIN: 0.20,
    OPEN_RATE_MAX: 0.40,
    CLICK_RATE_MIN: 0.05,
    CLICK_RATE_MAX: 0.15,
    CONVERT_RATE_MIN: 0.01,
    CONVERT_RATE_MAX: 0.03,
  }
}

export default CONSTANTS;
